/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Java_MySqlConnect;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class Java_MySqlConnect extends javax.swing.JFrame {

    /**
     * Creates new form Java_MySqlConnect
     */
    public Java_MySqlConnect() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLblEnroll = new javax.swing.JLabel();
        jTxtEnrollmentNo = new javax.swing.JTextField();
        jLblFirstname = new javax.swing.JLabel();
        jTxtFirstname = new javax.swing.JTextField();
        jLblLastname = new javax.swing.JLabel();
        jTxtLastname = new javax.swing.JTextField();
        jLblStudentID = new javax.swing.JLabel();
        jTxtStudentID = new javax.swing.JTextField();
        jLblAddress = new javax.swing.JLabel();
        jTxtAddress = new javax.swing.JTextField();
        jLblMobile = new javax.swing.JLabel();
        jTxtMobileNo = new javax.swing.JTextField();
        resultLbl = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jbtnUpdate = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jbtnAddNew = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, 190, 290));

        jLblEnroll.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLblEnroll.setText("Enrollment No.");
        jPanel2.add(jLblEnroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jTxtEnrollmentNo.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jPanel2.add(jTxtEnrollmentNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 460, -1));

        jLblFirstname.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLblFirstname.setText("Firstname");
        jPanel2.add(jLblFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jTxtFirstname.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jTxtFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFirstnameActionPerformed(evt);
            }
        });
        jPanel2.add(jTxtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 460, -1));

        jLblLastname.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLblLastname.setText("Lastname");
        jPanel2.add(jLblLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jTxtLastname.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jPanel2.add(jTxtLastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 460, -1));

        jLblStudentID.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLblStudentID.setText("Student ID");
        jPanel2.add(jLblStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jTxtStudentID.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jTxtStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtStudentIDActionPerformed(evt);
            }
        });
        jPanel2.add(jTxtStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 460, -1));

        jLblAddress.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLblAddress.setText("Address");
        jPanel2.add(jLblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jTxtAddress.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jPanel2.add(jTxtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 460, -1));

        jLblMobile.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLblMobile.setText("Mobile No.");
        jPanel2.add(jLblMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        jTxtMobileNo.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jTxtMobileNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtMobileNoActionPerformed(evt);
            }
        });
        jPanel2.add(jTxtMobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 460, -1));

        resultLbl.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        resultLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(resultLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 180, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 700, 500));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel1.setText("MySQL Connection");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 480, 50));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 940, 70));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 8));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, 190, 290));

        jbtnUpdate.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 190, 60));

        jbtnReset.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 190, 60));

        jbtnDelete.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 190, 60));

        jButton5.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 190, 60));

        jbtnAddNew.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jbtnAddNew.setText("Insert");
        jbtnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddNewActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnAddNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 190, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 230, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 980, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtStudentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtStudentIDActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        // TODO add your handling code here:
        jTxtStudentID.setText(null);
        jTxtFirstname.setText(null);
        jTxtLastname.setText(null);
        jTxtAddress.setText(null);
        jTxtEnrollmentNo.setText(null);
        resultLbl.setText(null);
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnDeleteActionPerformed
    private JFrame frame;
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to Exit", "MySQL Connector", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jbtnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddNewActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(jTxtStudentID.getText());
        String firstname = jTxtFirstname.getText();
        String lastname = jTxtLastname.getText();
        String address = jTxtAddress.getText();
        int enroll = Integer.parseInt(jTxtEnrollmentNo.getText());
        int mobile = Integer.parseInt(jTxtMobileNo.getText());
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/mydb", "root", "");
            System.out.println("Connection Established");
            
            String query1 = "insert into studentdb(id, firstname, lastname, address, enroll, mobile) " + "values(?,?,?,?,?,?)";
            
            PreparedStatement pst = con.prepareStatement(query1);
            pst.setInt(1, id);
            pst.setString(2, firstname);
            pst.setString(3, lastname);
            pst.setString(4, address);
            pst.setInt(5, enroll);
            pst.setInt(6, mobile);
            
            int i = pst.executeUpdate();
            resultLbl.setText(i + " row inserted");
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Java_MySqlConnect.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Java_MySqlConnect.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnAddNewActionPerformed

    private void jTxtFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFirstnameActionPerformed

    private void jTxtMobileNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtMobileNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtMobileNoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Java_MySqlConnect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Java_MySqlConnect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Java_MySqlConnect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Java_MySqlConnect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Java_MySqlConnect().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblAddress;
    private javax.swing.JLabel jLblEnroll;
    private javax.swing.JLabel jLblFirstname;
    private javax.swing.JLabel jLblLastname;
    private javax.swing.JLabel jLblMobile;
    private javax.swing.JLabel jLblStudentID;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTxtAddress;
    private javax.swing.JTextField jTxtEnrollmentNo;
    private javax.swing.JTextField jTxtFirstname;
    private javax.swing.JTextField jTxtLastname;
    private javax.swing.JTextField jTxtMobileNo;
    private javax.swing.JTextField jTxtStudentID;
    private javax.swing.JButton jbtnAddNew;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JLabel resultLbl;
    // End of variables declaration//GEN-END:variables
}
